// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/services/cancellation_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/expertise_event.dart' as _i2;
import 'package:spots/core/models/payment.dart' as _i6;
import 'package:spots/core/models/payment_intent.dart' as _i12;
import 'package:spots/core/models/payment_result.dart' as _i4;
import 'package:spots/core/models/revenue_split.dart' as _i5;
import 'package:spots/core/models/spot.dart' as _i10;
import 'package:spots/core/models/unified_user.dart' as _i9;
import 'package:spots/core/services/expertise_event_service.dart' as _i7;
import 'package:spots/core/services/payment_service.dart' as _i11;
import 'package:spots/core/services/revenue_split_service.dart' as _i13;
import 'package:spots/core/services/stripe_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExpertiseEvent_0 extends _i1.SmartFake
    implements _i2.ExpertiseEvent {
  _FakeExpertiseEvent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStripeService_1 extends _i1.SmartFake implements _i3.StripeService {
  _FakeStripeService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentResult_2 extends _i1.SmartFake implements _i4.PaymentResult {
  _FakePaymentResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRevenueSplit_3 extends _i1.SmartFake implements _i5.RevenueSplit {
  _FakeRevenueSplit_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayment_4 extends _i1.SmartFake implements _i6.Payment {
  _FakePayment_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExpertiseEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpertiseEventService extends _i1.Mock
    implements _i7.ExpertiseEventService {
  MockExpertiseEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.ExpertiseEvent> createEvent({
    required _i9.UnifiedUser? host,
    required String? title,
    required String? description,
    required String? category,
    required _i2.ExpertiseEventType? eventType,
    required DateTime? startTime,
    required DateTime? endTime,
    List<_i10.Spot>? spots,
    String? location,
    double? latitude,
    double? longitude,
    int? maxAttendees = 20,
    double? price,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [],
          {
            #host: host,
            #title: title,
            #description: description,
            #category: category,
            #eventType: eventType,
            #startTime: startTime,
            #endTime: endTime,
            #spots: spots,
            #location: location,
            #latitude: latitude,
            #longitude: longitude,
            #maxAttendees: maxAttendees,
            #price: price,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i8.Future<_i2.ExpertiseEvent>.value(_FakeExpertiseEvent_0(
          this,
          Invocation.method(
            #createEvent,
            [],
            {
              #host: host,
              #title: title,
              #description: description,
              #category: category,
              #eventType: eventType,
              #startTime: startTime,
              #endTime: endTime,
              #spots: spots,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #maxAttendees: maxAttendees,
              #price: price,
              #isPublic: isPublic,
            },
          ),
        )),
      ) as _i8.Future<_i2.ExpertiseEvent>);

  @override
  _i8.Future<_i2.ExpertiseEvent> duplicateEvent({
    required _i2.ExpertiseEvent? originalEvent,
    DateTime? newStartTime,
    bool? autoSuggestTime = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [],
          {
            #originalEvent: originalEvent,
            #newStartTime: newStartTime,
            #autoSuggestTime: autoSuggestTime,
          },
        ),
        returnValue: _i8.Future<_i2.ExpertiseEvent>.value(_FakeExpertiseEvent_0(
          this,
          Invocation.method(
            #duplicateEvent,
            [],
            {
              #originalEvent: originalEvent,
              #newStartTime: newStartTime,
              #autoSuggestTime: autoSuggestTime,
            },
          ),
        )),
      ) as _i8.Future<_i2.ExpertiseEvent>);

  @override
  _i8.Future<void> registerForEvent(
    _i2.ExpertiseEvent? event,
    _i9.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerForEvent,
          [
            event,
            user,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cancelRegistration(
    _i2.ExpertiseEvent? event,
    _i9.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRegistration,
          [
            event,
            user,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.ExpertiseEvent>> getEventsByHost(_i9.UnifiedUser? host) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByHost,
          [host],
        ),
        returnValue:
            _i8.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i8.Future<List<_i2.ExpertiseEvent>> getEventsByAttendee(
          _i9.UnifiedUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByAttendee,
          [user],
        ),
        returnValue:
            _i8.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i8.Future<_i2.ExpertiseEvent?> getEventById(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue: _i8.Future<_i2.ExpertiseEvent?>.value(),
      ) as _i8.Future<_i2.ExpertiseEvent?>);

  @override
  _i8.Future<List<_i2.ExpertiseEvent>> searchEvents({
    String? category,
    String? location,
    _i2.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [],
          {
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
          },
        ),
        returnValue:
            _i8.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i8.Future<List<_i2.ExpertiseEvent>> getUpcomingEventsInCategory(
    String? category, {
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEventsInCategory,
          [category],
          {#maxResults: maxResults},
        ),
        returnValue:
            _i8.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i8.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i8.Future<void> updateEventStatus(
    _i2.ExpertiseEvent? event,
    _i2.EventStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventStatus,
          [
            event,
            status,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i11.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.StripeService get stripeService => (super.noSuchMethod(
        Invocation.getter(#stripeService),
        returnValue: _FakeStripeService_1(
          this,
          Invocation.getter(#stripeService),
        ),
      ) as _i3.StripeService);

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.PaymentResult> purchaseEventTicket({
    required String? eventId,
    required String? userId,
    required double? ticketPrice,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseEventTicket,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #ticketPrice: ticketPrice,
            #quantity: quantity,
          },
        ),
        returnValue: _i8.Future<_i4.PaymentResult>.value(_FakePaymentResult_2(
          this,
          Invocation.method(
            #purchaseEventTicket,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #ticketPrice: ticketPrice,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i8.Future<_i4.PaymentResult>);

  @override
  _i5.RevenueSplit calculateRevenueSplit({
    required double? totalAmount,
    required int? ticketsSold,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRevenueSplit,
          [],
          {
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #eventId: eventId,
          },
        ),
        returnValue: _FakeRevenueSplit_3(
          this,
          Invocation.method(
            #calculateRevenueSplit,
            [],
            {
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #eventId: eventId,
            },
          ),
        ),
      ) as _i5.RevenueSplit);

  @override
  _i8.Future<_i6.Payment> confirmPayment({
    required String? paymentId,
    required String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [],
          {
            #paymentId: paymentId,
            #paymentIntentId: paymentIntentId,
          },
        ),
        returnValue: _i8.Future<_i6.Payment>.value(_FakePayment_4(
          this,
          Invocation.method(
            #confirmPayment,
            [],
            {
              #paymentId: paymentId,
              #paymentIntentId: paymentIntentId,
            },
          ),
        )),
      ) as _i8.Future<_i6.Payment>);

  @override
  _i8.Future<void> handlePaymentFailure({
    required String? paymentId,
    required String? errorMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePaymentFailure,
          [],
          {
            #paymentId: paymentId,
            #errorMessage: errorMessage,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i6.Payment? getPayment(String? paymentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPayment,
        [paymentId],
      )) as _i6.Payment?);

  @override
  _i12.PaymentIntent? getPaymentIntent(String? paymentIntentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentIntent,
        [paymentIntentId],
      )) as _i12.PaymentIntent?);

  @override
  List<_i6.Payment> getPaymentsForEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForEvent,
          [eventId],
        ),
        returnValue: <_i6.Payment>[],
      ) as List<_i6.Payment>);

  @override
  _i6.Payment? getPaymentForEventAndUser(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentForEventAndUser,
        [
          eventId,
          userId,
        ],
      )) as _i6.Payment?);

  @override
  _i8.Future<bool> hasPartnership(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #hasPartnership,
          [eventId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i5.RevenueSplit> calculatePartnershipRevenueSplit({
    required String? eventId,
    required double? totalAmount,
    required int? ticketsSold,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePartnershipRevenueSplit,
          [],
          {
            #eventId: eventId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
          },
        ),
        returnValue: _i8.Future<_i5.RevenueSplit>.value(_FakeRevenueSplit_3(
          this,
          Invocation.method(
            #calculatePartnershipRevenueSplit,
            [],
            {
              #eventId: eventId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
            },
          ),
        )),
      ) as _i8.Future<_i5.RevenueSplit>);

  @override
  _i8.Future<Map<String, double>> distributePartnershipPayment({
    required String? paymentId,
    required String? partnershipId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributePartnershipPayment,
          [],
          {
            #paymentId: paymentId,
            #partnershipId: partnershipId,
          },
        ),
        returnValue: _i8.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i8.Future<Map<String, double>>);
}

/// A class which mocks [RevenueSplitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRevenueSplitService extends _i1.Mock
    implements _i13.RevenueSplitService {
  MockRevenueSplitService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.RevenueSplit> calculateNWaySplit({
    required String? eventId,
    String? partnershipId,
    required double? totalAmount,
    required int? ticketsSold,
    required List<_i5.SplitParty>? parties,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateNWaySplit,
          [],
          {
            #eventId: eventId,
            #partnershipId: partnershipId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #parties: parties,
          },
        ),
        returnValue: _i8.Future<_i5.RevenueSplit>.value(_FakeRevenueSplit_3(
          this,
          Invocation.method(
            #calculateNWaySplit,
            [],
            {
              #eventId: eventId,
              #partnershipId: partnershipId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #parties: parties,
            },
          ),
        )),
      ) as _i8.Future<_i5.RevenueSplit>);

  @override
  _i8.Future<_i5.RevenueSplit> calculateFromPartnership({
    required String? partnershipId,
    required double? totalAmount,
    required int? ticketsSold,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFromPartnership,
          [],
          {
            #partnershipId: partnershipId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
          },
        ),
        returnValue: _i8.Future<_i5.RevenueSplit>.value(_FakeRevenueSplit_3(
          this,
          Invocation.method(
            #calculateFromPartnership,
            [],
            {
              #partnershipId: partnershipId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
            },
          ),
        )),
      ) as _i8.Future<_i5.RevenueSplit>);

  @override
  _i8.Future<_i5.RevenueSplit> lockSplit({
    required String? revenueSplitId,
    required String? lockedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lockSplit,
          [],
          {
            #revenueSplitId: revenueSplitId,
            #lockedBy: lockedBy,
          },
        ),
        returnValue: _i8.Future<_i5.RevenueSplit>.value(_FakeRevenueSplit_3(
          this,
          Invocation.method(
            #lockSplit,
            [],
            {
              #revenueSplitId: revenueSplitId,
              #lockedBy: lockedBy,
            },
          ),
        )),
      ) as _i8.Future<_i5.RevenueSplit>);

  @override
  _i8.Future<Map<String, double>> distributePayments({
    required String? revenueSplitId,
    required DateTime? eventEndTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributePayments,
          [],
          {
            #revenueSplitId: revenueSplitId,
            #eventEndTime: eventEndTime,
          },
        ),
        returnValue: _i8.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i8.Future<Map<String, double>>);

  @override
  _i8.Future<double> trackEarnings({
    required String? partyId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackEarnings,
          [],
          {
            #partyId: partyId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i8.Future<double>.value(0.0),
      ) as _i8.Future<double>);

  @override
  _i8.Future<_i5.RevenueSplit?> getRevenueSplit(String? revenueSplitId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRevenueSplit,
          [revenueSplitId],
        ),
        returnValue: _i8.Future<_i5.RevenueSplit?>.value(),
      ) as _i8.Future<_i5.RevenueSplit?>);

  @override
  _i8.Future<List<_i5.RevenueSplit>> getRevenueSplitsForEvent(
          String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRevenueSplitsForEvent,
          [eventId],
        ),
        returnValue:
            _i8.Future<List<_i5.RevenueSplit>>.value(<_i5.RevenueSplit>[]),
      ) as _i8.Future<List<_i5.RevenueSplit>>);

  @override
  _i8.Future<_i5.RevenueSplit> calculateNWayBrandSplit({
    required String? eventId,
    required double? totalAmount,
    required int? ticketsSold,
    Map<String, double>? brandPercentages,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateNWayBrandSplit,
          [],
          {
            #eventId: eventId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #brandPercentages: brandPercentages,
          },
        ),
        returnValue: _i8.Future<_i5.RevenueSplit>.value(_FakeRevenueSplit_3(
          this,
          Invocation.method(
            #calculateNWayBrandSplit,
            [],
            {
              #eventId: eventId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #brandPercentages: brandPercentages,
            },
          ),
        )),
      ) as _i8.Future<_i5.RevenueSplit>);

  @override
  _i8.Future<_i5.RevenueSplit> calculateProductSalesSplit({
    required String? productTrackingId,
    required double? totalSales,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateProductSalesSplit,
          [],
          {
            #productTrackingId: productTrackingId,
            #totalSales: totalSales,
          },
        ),
        returnValue: _i8.Future<_i5.RevenueSplit>.value(_FakeRevenueSplit_3(
          this,
          Invocation.method(
            #calculateProductSalesSplit,
            [],
            {
              #productTrackingId: productTrackingId,
              #totalSales: totalSales,
            },
          ),
        )),
      ) as _i8.Future<_i5.RevenueSplit>);

  @override
  _i8.Future<Map<String, _i5.RevenueSplit>> calculateHybridSplit({
    required String? eventId,
    required double? cashAmount,
    required double? productSalesAmount,
    required int? ticketsSold,
    required List<_i5.SplitParty>? parties,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateHybridSplit,
          [],
          {
            #eventId: eventId,
            #cashAmount: cashAmount,
            #productSalesAmount: productSalesAmount,
            #ticketsSold: ticketsSold,
            #parties: parties,
          },
        ),
        returnValue: _i8.Future<Map<String, _i5.RevenueSplit>>.value(
            <String, _i5.RevenueSplit>{}),
      ) as _i8.Future<Map<String, _i5.RevenueSplit>>);
}
