// Mocks generated by Mockito 5.4.6 from annotations
// in spots/test/unit/services/event_success_analysis_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spots/core/models/event_feedback.dart' as _i3;
import 'package:spots/core/models/expertise_event.dart' as _i2;
import 'package:spots/core/models/payment.dart' as _i7;
import 'package:spots/core/models/payment_intent.dart' as _i14;
import 'package:spots/core/models/payment_result.dart' as _i5;
import 'package:spots/core/models/revenue_split.dart' as _i6;
import 'package:spots/core/models/spot.dart' as _i11;
import 'package:spots/core/models/unified_user.dart' as _i10;
import 'package:spots/core/services/expertise_event_service.dart' as _i8;
import 'package:spots/core/services/payment_service.dart' as _i13;
import 'package:spots/core/services/post_event_feedback_service.dart' as _i12;
import 'package:spots/core/services/stripe_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExpertiseEvent_0 extends _i1.SmartFake
    implements _i2.ExpertiseEvent {
  _FakeExpertiseEvent_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventFeedback_2 extends _i1.SmartFake implements _i3.EventFeedback {
  _FakeEventFeedback_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStripeService_3 extends _i1.SmartFake implements _i4.StripeService {
  _FakeStripeService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentResult_4 extends _i1.SmartFake implements _i5.PaymentResult {
  _FakePaymentResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRevenueSplit_5 extends _i1.SmartFake implements _i6.RevenueSplit {
  _FakeRevenueSplit_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayment_6 extends _i1.SmartFake implements _i7.Payment {
  _FakePayment_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExpertiseEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpertiseEventService extends _i1.Mock
    implements _i8.ExpertiseEventService {
  MockExpertiseEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.ExpertiseEvent> createEvent({
    required _i10.UnifiedUser? host,
    required String? title,
    required String? description,
    required String? category,
    required _i2.ExpertiseEventType? eventType,
    required DateTime? startTime,
    required DateTime? endTime,
    List<_i11.Spot>? spots,
    String? location,
    double? latitude,
    double? longitude,
    int? maxAttendees = 20,
    double? price,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [],
          {
            #host: host,
            #title: title,
            #description: description,
            #category: category,
            #eventType: eventType,
            #startTime: startTime,
            #endTime: endTime,
            #spots: spots,
            #location: location,
            #latitude: latitude,
            #longitude: longitude,
            #maxAttendees: maxAttendees,
            #price: price,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i9.Future<_i2.ExpertiseEvent>.value(_FakeExpertiseEvent_0(
          this,
          Invocation.method(
            #createEvent,
            [],
            {
              #host: host,
              #title: title,
              #description: description,
              #category: category,
              #eventType: eventType,
              #startTime: startTime,
              #endTime: endTime,
              #spots: spots,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #maxAttendees: maxAttendees,
              #price: price,
              #isPublic: isPublic,
            },
          ),
        )),
      ) as _i9.Future<_i2.ExpertiseEvent>);

  @override
  _i9.Future<_i2.ExpertiseEvent> duplicateEvent({
    required _i2.ExpertiseEvent? originalEvent,
    DateTime? newStartTime,
    bool? autoSuggestTime = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateEvent,
          [],
          {
            #originalEvent: originalEvent,
            #newStartTime: newStartTime,
            #autoSuggestTime: autoSuggestTime,
          },
        ),
        returnValue: _i9.Future<_i2.ExpertiseEvent>.value(_FakeExpertiseEvent_0(
          this,
          Invocation.method(
            #duplicateEvent,
            [],
            {
              #originalEvent: originalEvent,
              #newStartTime: newStartTime,
              #autoSuggestTime: autoSuggestTime,
            },
          ),
        )),
      ) as _i9.Future<_i2.ExpertiseEvent>);

  @override
  _i9.Future<void> registerForEvent(
    _i2.ExpertiseEvent? event,
    _i10.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerForEvent,
          [
            event,
            user,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> cancelRegistration(
    _i2.ExpertiseEvent? event,
    _i10.UnifiedUser? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRegistration,
          [
            event,
            user,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i2.ExpertiseEvent>> getEventsByHost(
          _i10.UnifiedUser? host) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByHost,
          [host],
        ),
        returnValue:
            _i9.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i9.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i9.Future<List<_i2.ExpertiseEvent>> getEventsByAttendee(
          _i10.UnifiedUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByAttendee,
          [user],
        ),
        returnValue:
            _i9.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i9.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i9.Future<_i2.ExpertiseEvent?> getEventById(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue: _i9.Future<_i2.ExpertiseEvent?>.value(),
      ) as _i9.Future<_i2.ExpertiseEvent?>);

  @override
  _i9.Future<List<_i2.ExpertiseEvent>> searchEvents({
    String? category,
    String? location,
    _i2.ExpertiseEventType? eventType,
    DateTime? startDate,
    DateTime? endDate,
    int? maxResults = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [],
          {
            #category: category,
            #location: location,
            #eventType: eventType,
            #startDate: startDate,
            #endDate: endDate,
            #maxResults: maxResults,
          },
        ),
        returnValue:
            _i9.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i9.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i9.Future<List<_i2.ExpertiseEvent>> getUpcomingEventsInCategory(
    String? category, {
    int? maxResults = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingEventsInCategory,
          [category],
          {#maxResults: maxResults},
        ),
        returnValue:
            _i9.Future<List<_i2.ExpertiseEvent>>.value(<_i2.ExpertiseEvent>[]),
      ) as _i9.Future<List<_i2.ExpertiseEvent>>);

  @override
  _i9.Future<void> updateEventStatus(
    _i2.ExpertiseEvent? event,
    _i2.EventStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEventStatus,
          [
            event,
            status,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [PostEventFeedbackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostEventFeedbackService extends _i1.Mock
    implements _i12.PostEventFeedbackService {
  MockPostEventFeedbackService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<DateTime> scheduleFeedbackCollection(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleFeedbackCollection,
          [eventId],
        ),
        returnValue: _i9.Future<DateTime>.value(_FakeDateTime_1(
          this,
          Invocation.method(
            #scheduleFeedbackCollection,
            [eventId],
          ),
        )),
      ) as _i9.Future<DateTime>);

  @override
  _i9.Future<void> sendFeedbackRequests(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #sendFeedbackRequests,
          [eventId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.EventFeedback> submitFeedback({
    required String? eventId,
    required String? userId,
    required double? overallRating,
    required Map<String, double>? categoryRatings,
    String? comments,
    List<String>? highlights,
    List<String>? improvements,
    required bool? wouldAttendAgain,
    required bool? wouldRecommend,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitFeedback,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #overallRating: overallRating,
            #categoryRatings: categoryRatings,
            #comments: comments,
            #highlights: highlights,
            #improvements: improvements,
            #wouldAttendAgain: wouldAttendAgain,
            #wouldRecommend: wouldRecommend,
          },
        ),
        returnValue: _i9.Future<_i3.EventFeedback>.value(_FakeEventFeedback_2(
          this,
          Invocation.method(
            #submitFeedback,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #overallRating: overallRating,
              #categoryRatings: categoryRatings,
              #comments: comments,
              #highlights: highlights,
              #improvements: improvements,
              #wouldAttendAgain: wouldAttendAgain,
              #wouldRecommend: wouldRecommend,
            },
          ),
        )),
      ) as _i9.Future<_i3.EventFeedback>);

  @override
  _i9.Future<dynamic> submitPartnerRating({
    required String? eventId,
    required String? raterId,
    required String? ratedId,
    required String? partnershipRole,
    required double? overallRating,
    required double? professionalism,
    required double? communication,
    required double? reliability,
    required double? wouldPartnerAgain,
    String? positives,
    String? improvements,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitPartnerRating,
          [],
          {
            #eventId: eventId,
            #raterId: raterId,
            #ratedId: ratedId,
            #partnershipRole: partnershipRole,
            #overallRating: overallRating,
            #professionalism: professionalism,
            #communication: communication,
            #reliability: reliability,
            #wouldPartnerAgain: wouldPartnerAgain,
            #positives: positives,
            #improvements: improvements,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<List<_i3.EventFeedback>> getFeedbackForEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeedbackForEvent,
          [eventId],
        ),
        returnValue:
            _i9.Future<List<_i3.EventFeedback>>.value(<_i3.EventFeedback>[]),
      ) as _i9.Future<List<_i3.EventFeedback>>);

  @override
  _i9.Future<List<_i3.EventFeedback>> getEventFeedback(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventFeedback,
          [eventId],
        ),
        returnValue:
            _i9.Future<List<_i3.EventFeedback>>.value(<_i3.EventFeedback>[]),
      ) as _i9.Future<List<_i3.EventFeedback>>);

  @override
  _i9.Future<List<dynamic>> getPartnerRatingsForEvent(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPartnerRatingsForEvent,
          [eventId],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<List<dynamic>> getEventPartnerRatings(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventPartnerRatings,
          [eventId],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);
}

/// A class which mocks [PaymentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentService extends _i1.Mock implements _i13.PaymentService {
  MockPaymentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i4.StripeService get stripeService => (super.noSuchMethod(
        Invocation.getter(#stripeService),
        returnValue: _FakeStripeService_3(
          this,
          Invocation.getter(#stripeService),
        ),
      ) as _i4.StripeService);

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i5.PaymentResult> purchaseEventTicket({
    required String? eventId,
    required String? userId,
    required double? ticketPrice,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseEventTicket,
          [],
          {
            #eventId: eventId,
            #userId: userId,
            #ticketPrice: ticketPrice,
            #quantity: quantity,
          },
        ),
        returnValue: _i9.Future<_i5.PaymentResult>.value(_FakePaymentResult_4(
          this,
          Invocation.method(
            #purchaseEventTicket,
            [],
            {
              #eventId: eventId,
              #userId: userId,
              #ticketPrice: ticketPrice,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i9.Future<_i5.PaymentResult>);

  @override
  _i6.RevenueSplit calculateRevenueSplit({
    required double? totalAmount,
    required int? ticketsSold,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRevenueSplit,
          [],
          {
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
            #eventId: eventId,
          },
        ),
        returnValue: _FakeRevenueSplit_5(
          this,
          Invocation.method(
            #calculateRevenueSplit,
            [],
            {
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
              #eventId: eventId,
            },
          ),
        ),
      ) as _i6.RevenueSplit);

  @override
  _i9.Future<_i7.Payment> confirmPayment({
    required String? paymentId,
    required String? paymentIntentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [],
          {
            #paymentId: paymentId,
            #paymentIntentId: paymentIntentId,
          },
        ),
        returnValue: _i9.Future<_i7.Payment>.value(_FakePayment_6(
          this,
          Invocation.method(
            #confirmPayment,
            [],
            {
              #paymentId: paymentId,
              #paymentIntentId: paymentIntentId,
            },
          ),
        )),
      ) as _i9.Future<_i7.Payment>);

  @override
  _i9.Future<void> handlePaymentFailure({
    required String? paymentId,
    required String? errorMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handlePaymentFailure,
          [],
          {
            #paymentId: paymentId,
            #errorMessage: errorMessage,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i7.Payment? getPayment(String? paymentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPayment,
        [paymentId],
      )) as _i7.Payment?);

  @override
  _i14.PaymentIntent? getPaymentIntent(String? paymentIntentId) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentIntent,
        [paymentIntentId],
      )) as _i14.PaymentIntent?);

  @override
  List<_i7.Payment> getPaymentsForEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #getPaymentsForEvent,
          [eventId],
        ),
        returnValue: <_i7.Payment>[],
      ) as List<_i7.Payment>);

  @override
  _i7.Payment? getPaymentForEventAndUser(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getPaymentForEventAndUser,
        [
          eventId,
          userId,
        ],
      )) as _i7.Payment?);

  @override
  _i9.Future<bool> hasPartnership(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #hasPartnership,
          [eventId],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i6.RevenueSplit> calculatePartnershipRevenueSplit({
    required String? eventId,
    required double? totalAmount,
    required int? ticketsSold,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePartnershipRevenueSplit,
          [],
          {
            #eventId: eventId,
            #totalAmount: totalAmount,
            #ticketsSold: ticketsSold,
          },
        ),
        returnValue: _i9.Future<_i6.RevenueSplit>.value(_FakeRevenueSplit_5(
          this,
          Invocation.method(
            #calculatePartnershipRevenueSplit,
            [],
            {
              #eventId: eventId,
              #totalAmount: totalAmount,
              #ticketsSold: ticketsSold,
            },
          ),
        )),
      ) as _i9.Future<_i6.RevenueSplit>);

  @override
  _i9.Future<Map<String, double>> distributePartnershipPayment({
    required String? paymentId,
    required String? partnershipId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #distributePartnershipPayment,
          [],
          {
            #paymentId: paymentId,
            #partnershipId: partnershipId,
          },
        ),
        returnValue: _i9.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i9.Future<Map<String, double>>);
}
